### ISSUE TITLE
Wrong response code and visualization

### ISSUE THREAD

**Issue by manuelselbach** [cobwebch/flush_language_cache#11]
It turned out, that the command returns the wrong codes. In case of success it returns 1 which is meant to be an error and for an error it returns 0. Previously there where the constants of Symfony Command used which where correct:

![Bildschirmfoto 2020-06-03 um 14 43 55](https://user-images.githubusercontent.com/4679794/83640272-3166cc80-a5ac-11ea-967c-7f677eff9448.png)

Furthermore, in case of an error, the output is shown in style of "success" which also may lead to different interpretation as intended.

**Comment by fsuter** [comment]
It seems like I got it wrong in the end. I had started using the Symfony console constants, but then realized that it was not okay because it failed on installations where Symfony console was in an older version.

Looking at the code, I did quite a mix up :-\ I'll release a bug fix quickly.

Thanks for reporting.

**Comment by manuelselbach** [comment]
I've prepared already something ;)

PR is about to be created.
